name: ppicker
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip<24.1
  - setuptools
  - wheel
  - cmake
  - ffmpeg
  - ipykernel
  - numpy=1.26
  - scipy
  - pandas=1.5.3
  - scikit-learn
  - scikit-image
  - pillow
  - tqdm
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pytorch-cuda=11.8
  - torchtriton
  - napari=0.4.18
  - pyside6>=6.6
  - qtpy
  - mrcfile
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.2
      - aiohttp==3.10.7
      - aiosignal==1.3.1
      - alembic==1.13.3
      - art==6.3
      - astunparse==1.6.3
      - blosc2==2.7.1
      - cloudpickle==3.0.0
      - colorlog==6.8.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - dask==2024.9.1
      - dnspython==2.6.1
      - expecttest==0.2.1
      - fire==0.6.0
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gdown==5.2.0
      - greenlet==3.1.1
      - grpcio==1.66.1
      - h5py==3.12.1
      - hypothesis==6.108.4
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning-lite==1.8.0.post1
      - lightning-utilities==0.3.0
      - lintrunner==0.12.5
      - llvmlite==0.43.0
      - locket==1.0.0
      - mako==1.3.5
      - markdown==3.7
      - matplotlib==3.9.2
      - monai==1.3.2
      - mrcfile==1.5.3
      - msgpack==1.1.0
      - multidict==6.1.0
      - mysql-connector-python==9.0.0
      - ndindex==1.9.2
      - ninja==1.11.1.1
      - numba==0.60.0
      - numexpr==2.10.1
      - opencv-python==4.10.0.84
      - optree==0.12.1
      - optuna==4.0.0
      - pandas==1.5.3
      - partd==1.4.2
      - protobuf==5.28.2
      - py-cpuinfo==9.0.0
      - pycm==4.0
      - pyparsing==3.1.4
      - pystardb==0.4.3
      - python-etcd==0.4.5
      - pytorch-lightning==1.8.0.post1
      - pytorch-metric-learning==2.6.0
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - segment-anything==1.0
      - setuptools-scm==8.1.0
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.35
      - sympy==1.13.1
      - tables==3.10.1
      - tabulate==0.9.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - tomotwin-cryoet==0.9.0
      - toolz==0.12.1
      - torchelastic==0.2.2
      - torchmetrics==0.11.4
      - types-dataclasses==0.6.6
      - tzdata==2024.2
      - werkzeug==3.0.4
      - yarl==1.13.1
      - zipp==3.20.2
